[package]
name = "Phantester"
version = "0.1.0"
authors = ["Kinesys <67867993+Kinesys@users.noreply.github.com>"]
edition = "2018"

[dependencies]

#settng(Commands)

phantester = {version = "1", features = [] }
